LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

BROKER:
  host: '0.0.0.0:5671'
  cert_db: '/secrets/rabbitmq/ca_certificate.pem'
  sasl_user: 'ny-consumer'
  sasl_password: 'ny'

SUBSCRIPTION-MANAGER:
  host: 'localhost:8080'
  https: false
  timeout: 30
  verify: false

SWIM_EXPLORER_SM_USER: 'swim-explorer'
SWIM_EXPLORER_SM_PASS: 'swim-explorer'
